### ISSUE TITLE
Questions about Sawn block

### ISSUE THREAD

**Issue by wangruofan97** [zhangqianhui/Sawn#13]
Hi, thanks for your great work. I notice that when you warp weight and bias in Sawn block, you use 
`weight_warped = model(self.weight_ref, x, self.flow_ref)` and `bias_warped = model(self.bias_ref, x, self.flow_ref)`. 

It seems that this 'model' represents the `ExtractorAttn` class in GFLA. How does this method work as a warping operation? Thank you in advance for your reply.

**Comment by zhangqianhui** [comment]
Yes. You are right. It is global-flow and local attention module. I think it will better to read the paper of GFLA to know about the details. And we use the same flow code as the original flow fileld.

**Comment by wangruofan97** [comment]
I think that in GFLA they use this module to warp&mask features extracted from the input image. So does it act the same way on λ and β in Sawn block? The equation(4) in your paper looks like a simple bilinear sampling operation.

**Comment by zhangqianhui** [comment]
Yes. Please check the implementation details.

**Comment by wangruofan97** [comment]
OK, thank you.
