### ISSUE TITLE
Regarding the code release

### ISSUE THREAD

**Issue by vinits5** [zhangqianhui/Sawn#2]
Hi,

Really appreciate your research work. The results look really amazing.
When are you planning to release the code and pertained models for this research? It doesn't seem easy to reproduce the results by writing the code by our own. Hoping for a positive response.

**Comment by zhangqianhui** [comment]
Hi
I will release the code next month.

*Jichao Zhang, Ph.D.*
Department of Engineering and Computer Science
University of Trento
Via Sommarive 9 – I-38123 Trento – Italy

Phone: +39 3809087226
