### ISSUE TITLE
About figure 4 in your paper

### ISSUE THREAD

**Issue by IMSEMZPZ** [zhangqianhui/Sawn#3]
Thanks for the great work. I have some questions about figure 4 in the paper. 1) The input of the Pose Encoder seems to be misused as the target pose. 2) In the self-training process, is the Flow Encoder still calculating the optical flow from the sources to the targets? The flow seems to warp the (λ^i and β^i) which are aligned with the source pose.

**Comment by zhangqianhui** [comment]
I will release the code recently.
